# Generated by Django 5.0.3 on 2024-06-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/images/')),
                ('code_link', models.URLField(max_length=256)),
                ('live_link', models.URLField(max_length=256)),
            ],
        ),
    ]
