# Generated by Django 5.0.3 on 2024-06-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to='skills/images/')),
                ('title', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=200)),
            ],
        ),
    ]
